config/routes.rb
Rails.application.routes.draw do
  root "decks#index"
  
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users do
    get '/saved', to: 'users#saved'
    get '/created', to: 'users#created'
  end

  resources :decks do
    get '/study', to: 'decks#study'
    get '/save', to: 'decks#save'
    get '/unsave', to: 'decks#unsave'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :deck
    validates :front, presence: true
    validates :back, presence: true
end

app/models/deck.rb
class Deck < ApplicationRecord
    belongs_to :user
    has_many :cards
    accepts_nested_attributes_for :cards, allow_destroy: true

    def cards_atributes=(cards_attributes)
        cards_attributes.each_with_index do |card_attributes, i|
            if card_attributes.front.length > 0 && card_attributes.back.length > 0
                self.cards.build(card_attributes)
            end
        end
    end

    validates :title, presence: true, length: {maximum: 50}
    validates :description, presence: true, length: {maximum: 500}
    validates :cards, presence: true
end

app/models/save.rb
class Save < ApplicationRecord
    belongs_to :user
    validates :deck_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :decks
    has_many :saves, class_name: "Save"
    validates :username, presence: true
    validates_uniqueness_of :username, case_sensitive: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/decks_controller.rb
include ApplicationHelper

class DecksController < ApplicationController

  def index
    @decks = Deck.all
  end

  def show
    @deck = Deck.find(params[:id])
  end

  def study
    @deck = Deck.find(params[:deck_id])
  end

  def new
    @deck = Deck.new
    @deck.cards.build
  end

  def create
    @deck = Deck.new(deck_params
      .merge(user_id: current_user.id)
      .merge(creator: current_user.username)
      .merge(saves: 0))

    if @deck.save
      redirect_to @deck
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @deck = Deck.find(params[:id])
  end

  def update
    @deck = Deck.find(params[:id])

    if @deck.update(deck_params)
      redirect_to @deck
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy

    redirect_to root_path, status: :see_other
  end

  def save
    @deck = Deck.find(params[:deck_id])
    @deck.saves += 1
    @deck.save
    current_user.saves.build({deck_id: @deck.id})
    current_user.save
    redirect_to @deck
  end

  def unsave
    @deck = Deck.find(params[:deck_id])
    @deck.saves -= 1
    @deck.save
    current_user.saves.destroy(Save.find_by(deck_id: @deck.id))
    current_user.save
    redirect_to @deck
  end

  private
  
  def deck_params
    params.require(:deck).permit(:title, :description, :user_id,
      :saves, {cards_attributes: [:front, :back, :_destroy, :id]})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(username: params[:username])

    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/decks'
    else
      redirect_to login_path, notice: 'Username or password incorrect'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @user = User.find(params[:id])
        puts @user.saves
    end

    def saved
        @user = User.find(params[:user_id])
    end

    def created
        @user = User.find(params[:user_id])
    end

    private
    
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation, :decks, :saves)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/decks/_card_fields.html.erb
<div class='nested-fields'>
    <%= f.text_field :front %>
    <%= f.text_field :back %>
    <%= link_to_remove_association '<button>Remove Card</button>'.html_safe, f %>
</div>

app/views/decks/_form.html.erb
<%= form_for @deck, html: {autocomplete: 'off'} do |f| %>

    <h3>Title</h3>
    <%= f.text_field :title %><br><br>

    <h3>Description</h3>
    <%= f.text_field :description %><br><br>

    <h3>Cards</h3>
    <div id='cards'>
        <%= f.fields_for :cards do |card| %>
            <%= render 'card_fields', f: card %>
        <% end %>
        <%= link_to_add_association '<button>Add Card</button>'.html_safe, f, :cards %>
    </div>
    <br>

    <% if @deck.errors.present? %>
        <div class='error-list'>
            <% @deck.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </div>
    <% end %>

    <%= f.submit %>
<% end %>

app/views/decks/_logged_in_show.html.erb
<% in_user_saves = false %>
<% current_user.saves.each do |save| %>
    <% if save.deck_id == @deck.id %>
        <% in_user_saves = true %>
    <% end %>
<% end %>
<% if in_user_saves %>
    <%= link_to '<button>Unsave Deck</button>'.html_safe, deck_unsave_path(@deck) %>
<% else %>
    <%= link_to '<button>Save Deck</button>'.html_safe, deck_save_path(@deck) %>
<% end %>

<%= link_to '<button>Study Cards</button>'.html_safe, deck_study_path(@deck) %>

<% if current_user.id == @deck.user_id %>
    <%= link_to '<button>Edit Deck</button>'.html_safe, edit_deck_path(@deck) %>
    <%= link_to "<button class='delete'>Delete Deck</button>".html_safe, deck_path(@deck),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %><br>
<% end %>

app/views/decks/_logged_out_show.html.erb
<div class='greyed-out'>You need to be logged in to save decks.</div>

<%= link_to '<button>Study Cards</button>'.html_safe, deck_study_path(@deck) %>

app/views/decks/_login_logout.html.erb
<div class='login-logout'>
    <% if logged_in? %>
        Logged in as
        <span class='username'><%= link_to current_user.username, current_user %></span>
        <%= link_to '<button>Log Out</button>'.html_safe, '/logout' %>
    <% else %>
        <%= link_to '<button>Log In</button>'.html_safe, '/login' %>
    <% end %>
</div>

app/views/decks/_sidebar.html.erb
<style>
    body {
        display: grid;
        grid-template-areas: 's m';
        grid-template-columns: min-content auto;
    }
    div.main {
        grid-area: 'm';
    }
    div.sidebar {
        width: min-content;
        height: min-content;
        background-color: #d5d9db;
        margin: 150px 16px 0 0;
        border-radius: 12px;
        grid-area: 's';
    }
    button.sidebar-item {
        width: 100%;
        padding: 10px 16px;
        margin: 0;
        border-radius: 12px;
        color: #4b6a7e;
        background-color: #d5d9db;
        font-size: 18px;
        font-weight: bold;
        text-align: left;
        transition-duration: 150ms;
    }
    button.sidebar-item:hover {
        cursor: pointer;
        color: #1f3847;
        background-color: #c0c6c9;
        transition-duration: 150ms;
    }
</style>

<div class='sidebar'>
    <%= link_to "<button class='sidebar-item' id='top'>Top</button>".html_safe, root_path %>
    <%= link_to "<button class='sidebar-item' id='newest'>Newest</button>".html_safe, root_path %>
    <% if logged_in? %>
        <%= link_to "<button class='sidebar-item' id='saved'>Saved</button>".html_safe, user_saved_path(current_user) %>
        <%= link_to "<button class='sidebar-item' id='created'>Created</button>".html_safe, user_created_path(current_user) %>
    <% end %>
</div>

app/views/decks/edit.html.erb
<h1>Edit Deck</h1>

<% if logged_in? and current_user.id == @deck.user_id %>
    <%= render 'form', deck: @deck %>
<% else %>
    You do not have permission to edit this deck<br>
<% end %>

<%= link_to '<button>Cancel</button>'.html_safe, deck_path(@deck) %>

app/views/decks/index.html.erb
<style>
    .sidebar-item#top {
        color: #a55a8e;
        background-color: #c0c6c9;
    }
</style>

<%= render 'sidebar' %>

<div class='main'>
    <%= render 'login_logout' %>

    <h1>Decks</h1>
    
    <div style='margin: 8px 0'>
        <% if logged_in? %>
            <%= link_to "<button id='new-deck'>New Deck</button>".html_safe, new_deck_path %>
        <% else %>
            <button class='greyed-out' id='new-deck'>You must be logged in to create a new deck.</button>
        <% end %>
    </div>

    <table>
        <tr>
            <th style='width: 200px'>Deck</th>
            <th style='width: 70px'>Cards</th>
            <th style='width: 100px'>Created By</th>
            <th style='width: 70px'>Saves</th>
        </tr>
        <% @decks.each do |deck| %>
            <tr>
                <td><%= link_to deck.title, deck %></td>
                <td style='text-align: center'><%= deck.cards.length %></td>
                <td><%= deck.creator %></td>
                <td style='text-align: center'><%= deck.saves %></td>
            </tr>
        <% end %>
    </table>
</div>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<% if logged_in? %>
    <%= render 'form', deck: @deck %>
<% else %>
    You must be logged in to create a new deck.<br><br>
<% end %>

<%= link_to '<button>Cancel</button>'.html_safe, root_path %>

app/views/decks/show.html.erb
<%= render 'sidebar' %>

<div class='main'>
    <h1><%= @deck.title %></h1>

    <% if @deck.cards.length == 1 %>
        <div>1 card</div>
    <% else %>
        <div><%= @deck.cards.length %> cards</div>
    <% end %>

    <h3>Created by <%= link_to @deck.creator, User.find_by_username(@deck.creator) %></h3>

    <div class='description'><%= @deck.description %></div><br>

    <% if logged_in? %>
        <%= render 'logged_in_show', deck: @deck %>
    <% else %>
        <%= render 'logged_out_show', deck: @deck %>
    <% end %>

    <h3>Card list:</h3>
    <table>
        <tr>
            <th style='width: 40px; border: none'></th>
            <th style='width:150px'>Front</th>
            <th style='width:150px'>Back</th>
        </tr>
        <% @deck.cards.each_with_index do |card, i| %>
            <tr>
                <td style='text-align: center'><%= i + 1 %></td>
                <td><%= card.front %></td>
                <td><%= card.back %></td>
            </tr>
        <% end %>
    </table>
</div>

app/views/decks/study.erb
<script>
    var cardList = [];
    <% @deck.cards.each do |card| %>
        cardList.push({
            front: '<%= raw card.front %>',
            back: '<%= raw card.back %>'
        });
    <% end %>

    function flip(num) {
        var elem = document.getElementById('card_' + num);
        if (cardList[num].front === elem.innerHTML) {
            elem.innerHTML = cardList[num].back;
        } else {
            elem.innerHTML = cardList[num].front;
        }
    }
</script>

<h1><%= @deck.title %></h1>

<h3>Created by <%= @deck.creator %></h3>

<% @deck.cards.each_with_index do |card, i| %>
    <button onclick="flip('<%= i %>')" class='card' id='card_<%= i %>'><%= card.front %></button><br>
<% end %>

<%= link_to '<button>Back</button>'.html_safe, deck_path(@deck) %>

app/views/decks/study.html.erb
<script>
    var cardList = [];
    <% @deck.cards.each do |card| %>
        cardList.push({
            front: '<%= raw card.front %>',
            back: '<%= raw card.back %>'
        });
    <% end %>

    function flip(num) {
        var elem = document.getElementById('card_' + num);
        if (cardList[num].front === elem.innerHTML) {
            elem.innerHTML = cardList[num].back;
        } else {
            elem.innerHTML = cardList[num].front;
        }
    }
</script>

<h1><%= @deck.title %></h1>

<h3>Created by <%= link_to @deck.creator, User.find_by_username(@deck.creator) %></h3>

<% @deck.cards.each_with_index do |card, i| %>
    <button onclick="flip('<%= i %>')" class='card' id='card_<%= i %>'><%= card.front %></button><br>
<% end %>

<%= link_to '<button>Back</button>'.html_safe, deck_path(@deck) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capstone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>

app/views/users/created.html.erb
<style>
    .sidebar-item#created {
        color: #a55a8e;
        background-color: #c0c6c9;
    }
</style>

<%= render 'decks/sidebar' %>

<div class='main'>
    <%= render 'decks/login_logout' %>

    <h1><%= link_to @user.username, @user %>'s decks</h1>

    <table>
        <tr>
            <th style='width: 200px'>Deck</th>
            <th style='width: 70px'>Cards</th>
            <th style='width: 70px'>Saves</th>
        </tr>
        <% @user.decks.each do |deck| %>
            <tr>
                <td><%= link_to deck.title, deck %></td>
                <td style='text-align: center'><%= deck.cards.length %></td>
                <td style='text-align: center'><%= deck.saves %></td>
            </tr>
        <% end %>
    </table>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
<ul>
    <li><%= user.username %></li>
</ul>
<% end %>

app/views/users/new.html.erb
<style>
    div.field_with_errors { display: inline; }
    div { margin-bottom: 4px; }
</style>

<h1>New User</h1>

<%= link_to '<button>Log Into an Existing Account</button>'.html_safe, '/login' %>

<%= form_for @user, html: {autocomplete: 'off'} do |f| %>
    Username: <%= f.text_field :username %><br>
    Password: <%= f.password_field :password %><br>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <%= f.submit 'Create Account' %>
<% end %>

<%= link_to '<button>Back</button>'.html_safe, root_path %>

app/views/users/saved.html.erb
<style>
    .sidebar-item#saved {
        color: #a55a8e;
        background-color: #c0c6c9;
    }
</style>

<%= render 'decks/sidebar' %>

<div class='main'>
    <%= render 'decks/login_logout' %>
    
    <h1><%= link_to @user.username, @user %>'s saved decks</h1>

    <table>
        <tr>
            <th style='width: 200px'>Deck</th>
            <th style='width: 70px'>Cards</th>
            <th style='width: 70px'>Saves</th>
        </tr>
        <% @user.saves.each do |save| %>
            <% deck = Deck.find_by_id(save.deck_id) %>
            <% if !deck.nil? %>
                <tr>
                    <td><%= link_to deck.title, deck %></td>
                    <td style='text-align: center'><%= deck.cards.length %></td>
                    <td style='text-align: center'><%= deck.saves %></td>
                </tr>
            <% end %>
        <% end %>
    </table>
</div>

app/views/users/show.html.erb
<%= render 'decks/sidebar' %>

<div class='main'>
    <h1><%= @user.username %></h1>

    <h3>Created Decks</h3>

    <% @user.decks.each do |deck| %>
        <li><%= link_to deck.title, deck %></li>
    <% end %>

    <h3>Saved Decks</h3>

    <% @user.saves.each do |save| %>
        <% deck = Deck.find_by_id(save.deck_id) %>
        <% if !deck.nil? %>
            <li><%= link_to deck.title, deck %></li>
        <% end %>
    <% end %>
</div>